#include <mips.h>
#include "../dodojr.h"

        .text

        /*
        *# Original address: 0x809f7094
        */
/*
        .set            noreorder
        .set            noat
        .global         En_Dodojr_f17
        .ent            En_Dodojr_f17

En_Dodojr_f17:        


 THIS IS NOT A FUNCTION
        jr      ra
        nop

        
        .end            En_Dodojr_f17
        .set            at
        .set            reorder
*/
